
default:    build

# clean:
#	    rm -rf Makefile objs

build:
	    $(MAKE) -f ccc/Makefile
	    $(MAKE) -f cpp/Makefile

install:
	    $(MAKE) -f objs/Makefile install

modules:
	    $(MAKE) -f objs/Makefile modules

