#!/bin/sh
# cat see_future_time | while read LINE
#do
#   $kk =  `echo $LINE | awk "{print $2}"`
#    echo $kk
#done
kk="mm" ;
if [ "$kk" != "#" ]; then
    echo $kk
fi


awk '{print $1}' $HOME/see/etc/tbl/see_future_time | while read kk
do
#    echo $kk
    if [ "$kk" != "#" ]; then
        echo "create table "$kk"_1s("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"


        echo "create table "$kk"_2s("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_3s("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_5s("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_10s("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_15s("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_20s("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_30s("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_1f("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_2f("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_3f("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_5f("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_10f("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_15f("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_20f("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_30f("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_1h("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_2h("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_3h("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_4h("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_5h("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_6h("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_8h("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_10h("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_12h("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_1d("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_1w("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_1m("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_1j("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

        echo "create table "$kk"_1y("
        echo "    InstrumentID            CHAR(7),"
        echo "    TradingDay              CHAR(8),"
        echo "    UpdateTime              CHAR(8),"
        echo "    OpenPrice               DOUBLE,"
        echo "    HighestPrice            DOUBLE,"
        echo "    LowestPrice             DOUBLE,"
        echo "    ClosePrice              DOUBLE,"
        echo "    Volume                  INT,"
        echo "    PRIMARY KEY ( TradingDay,UpdateTime )"
        echo ");"

    fi
done
