
CC:=g++
CCFLAGS := -g -Wall -O3

ALLINC = -I ccc/com/inc \
		-I /usr/local/include/nanomsg \
		-I /usr/local/include/zdb \

CTPINC:= ./ctp/
CTPLIB:= ./ctp/
CTPLIBS:= ./ctp/thostmduserapi.so \
		./ctp/thosttraderapi.so


COMINC:= ./com/inc/
COMOBJ:= ./com/obj/
COMSRC:= ./com/src/

DBSINC:= ./dbs/inc/
DBSOBJ:= ./dbs/obj/
DBSSRC:= ./dbs/src/

FSSINC:= ./fss/inc/
FSSOBJ:= ./fss/obj/
FSSSRC:= ./fss/src/

IOSINC:= ./ios/inc/
IOSOBJ:= ./ios/obj/
IOSSRC:= ./ios/src/

INDINC:= ./ind/inc/
INDOBJ:= ./ind/obj/
INDSRC:= ./ind/src/

STGINC:= ./stg/inc/
STGOBJ:= ./stg/obj/
STGSRC:= ./stg/src/

MDSINC:= c++/mds/inc/
MDSOBJ:= c++/mds/obj/
MDSSRC:= c++/mds/src/

TDSINC:= ./tds/inc/
TDSOBJ:= ./tds/obj/
TDSSRC:= ./tds/src/

ETCTBL= ../etc/tbl/
BINEXE= ../bin/exe/
BINOBJ= ../bin/obj/

FILES = $(MDSSRC)main_md.cpp \
		$(MDSSRC)MdSpi.cpp

CCCOBJ:= \
     ccc/com/obj/see_errlog.o \
     ccc/com/obj/see_signal.o \
     ccc/com/obj/see_daemon.o \
     ccc/com/obj/see_bars.o \
     ccc/com/obj/see_pubsub.o \
     ccc/com/obj/see_iofile.o \
     ccc/com/obj/see_future.o

TSTOBJS = $(MDSOBJ)main_md.o \
		  $(MDSOBJ)MdSpi.o

CTPOBJS = $(MDSOBJ)see_ctpget.o \
		  $(MDSOBJ)MdSpi.o

# all := $(BINEXE)sss.x
all := $(BINEXE)ctpget.x

$(BINEXE)sss.x: $(TSTOBJS) \
					$(COMOBJS)
		$(CC) -o $(BINEXE)sss.x $(TSTOBJS) $(CCCOBJ) $(CTPLIBS) -lzdb -lnanomsg

$(BINEXE)ctpget.x: $(CTPOBJS) \
					$(COMOBJS)
		$(CC) -o $(BINEXE)ctpget.x $(CTPOBJS) $(CCCOBJ) $(CTPLIBS) -lzdb -lnanomsg

$(MDSOBJ)see_ctpget.o: $(MDSSRC)see_ctpget.cpp
		$(CC) $(CCFLAGS) $(ALLINC) -I$(MDSINC) -c $(MDSSRC)see_ctpget.cpp
		mv see_ctpget.o $(MDSOBJ)

$(MDSOBJ)main_md.o: $(MDSSRC)main_md.cpp
		$(CC) $(CCFLAGS) $(ALLINC) -I$(MDSINC) -c $(MDSSRC)main_md.cpp
		mv main_md.o $(MDSOBJ)

$(MDSOBJ)MdSpi.o: $(MDSSRC)MdSpi.cpp
		$(CC) $(CCFLAGS) $(ALLINC) -I$(MDSINC) -c $(MDSSRC)MdSpi.cpp
		mv MdSpi.o $(MDSOBJ)
